[package]
name = "key_hasher"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.0"
clap = { version = "4.5.41", features = ["derive"] }
color-eyre = "0.6.5"

[dev-dependencies]
pretty_assertions = "1.4.1"
