[package]
name = "key_hasher"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.1"
clap = { version = "4.5.45", features = ["derive"] }
color-eyre = "0.6.5"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1"
pretty_assertions = "1.4.1"
