name: Docker

on:
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Image Build Check
        run: just docker-build-debug

  docker-healthcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Setup Docker Network
        run: just pg-init-network
      - name: Startup PostgreSQL
        run: just pg-start
      - name: Install SQLx cli
        run: cargo install sqlx-cli --debug --no-default-features --features postgres --locked
      - name: Run SQLx Migration
        run: just sqlx-migrate
      - name: Image Build
        run: just docker-build-debug
      - name: Container Startup
        run: just docker-run-debug
      - name: Container Healthcheck
        run: just docker-healthcheck
      - name: Container Stop
        run: just docker-kill
