name: Markdown

on:
  pull_request:
    branches:
      - main

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Install markdownlint-cli2
        run: npm clean-install
      - name: MarkdownLint
        run: just markdownlint
