name: Python
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: PyRight Check
        run: just py-right-check

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Ruff Linting
        run: just py-ruff-check

  ruff-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Ruff Formatting
        run: just py-ruff-fmt-check

  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Pip-Audit Scan
        run: just py-audit
